Invalid argument for `--target`
In the *Downleveling* section, an invalid argument is passed for the `--target` flag, which results in an error: *error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.*

Also, the file to transpile is wrongly referenced as `input.ts` instead of `hello.ts`