fix: `jsx` is undefined by default, not preserve or react (#1102)
* fix: `jsx` is undefined by default, not preserve or react

- one gets an error when using JSX without configuring `jsx`:
  `error TS17004: Cannot use JSX unless the '--jsx' flag is provided.`

- TSConfig Reference said default was `react`, which is inaccurate
- Compiler Options said default was `preserve`, which is also inaccurate

- Add a `undefined` as the default in TSConfig Reference, same as
  allowUnrechableCode
- Remove the default in Compiler Options, same as all the other options
  without defaults

----
History:

Reference:
- `preserve` was written as the default in https://github.com/microsoft/TypeScript-Website/commit/eae5cc3ab38ddce1c0e70e36c223cb07bc734199#diff-444415c73770eafd0f9db7d708d74131R5
- But then was written as `react` in the body in https://github.com/microsoft/TypeScript-Website/commit/eae5cc3ab38ddce1c0e70e36c223cb07bc734199#diff-444415c73770eafd0f9db7d708d74131R5
- It was then switched to `react` in https://github.com/microsoft/TypeScript-Website/commit/450ae964411f5180e4c3f7e6e974ccba03eb4e59#diff-a912c6af3a16bf4288093c1264955bc6R120
- And then removed in https://github.com/microsoft/TypeScript-Website/commit/76b7d435fdbec8a4b88ac0b01b88e3fb72a829d1#diff-a912c6af3a16bf4288093c1264955bc6L120

Compiler Options:
- `preserve` was written as the default in https://github.com/microsoft/TypeScript-Website/commit/66f17ad4d0fa6b2b9fee791b0b7a729710aeb907#diff-bfc78b96c15b0ee906c1ab6176546dceR41

* Update Compiler Options.md

* Update Compiler Options.md

Co-authored-by: Orta Therox <ortam@microsoft.com>
Co-authored-by: Orta Therox <git@orta.io>